# Generated by Django 5.2.8 on 2025-11-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='descricao',
            field=models.TextField(default='Sem descrição'),
            preserve_default=False,
        ),
    ]
