# Generated by Django 5.2.8 on 2025-11-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_produtos_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qrcodes/'),
        ),
    ]
