# Generated by Django 5.2.8 on 2025-11-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_produtos_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='arquivo_certificacao',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
    ]
