# Generated by Django 5.2.8 on 2025-11-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('CLIENTE', 'Cliente Consumidor'), ('EMPRESA', 'Empresa Certificadora/Produtora')], default='CLIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome_companhia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
